version: '3.3'
services:
  product-service:
    #    image: observability-demo_product-service:latest
    build: ./product-service
    ports:
      - "5001:5001"
    # environment:
    #   - OTEL_SERVICE_NAME=product-service
    #   - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4317
    #   - OTEL_TRACES_EXPORTER=otlp
    #   - OTEL_METRICS_EXPORTER=otlp
    #   - OTEL_LOGS_EXPORTER=otlp
  cart-service:
    #    image: observability-demo_cart-service:latest
    build: ./cart-service
    ports:
      - "5002:5002"
    # environment:
    #   - OTEL_SERVICE_NAME=cart-service
    #   - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4317
    #   - OTEL_TRACES_EXPORTER=otlp
    #   - OTEL_METRICS_EXPORTER=otlp
    #   - OTEL_LOGS_EXPORTER=otlp
  order-service:
    #    image: observability-demo_order-service:latest
    build: ./order-service
    ports:
      - "5003:5003"
    # environment:
    #   - OTEL_SERVICE_NAME=order-service
    #   - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4317
    #   - OTEL_TRACES_EXPORTER=otlp
    #   - OTEL_METRICS_EXPORTER=otlp
    #   - OTEL_LOGS_EXPORTER=otlp
  frontend:
    #    image: observability-demo_frontend:latest
    build: ./frontend
    ports:
      - "5000:5000"
    # environment:
    #   - OTEL_SERVICE_NAME=frontend
    #   - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4317
    #   - OTEL_TRACES_EXPORTER=otlp
    #   - OTEL_METRICS_EXPORTER=otlp
    #   - OTEL_LOGS_EXPORTER=otlp
    depends_on:
      - product-service
      - cart-service
      - order-service
#   otel-collector:
#     image: otel/opentelemetry-collector:0.98.0
#     command: ["--config=/etc/otel-collector-config.yaml"]
#     volumes:
#       - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
#     ports:
#       - "4317:4317"   # gRPC
#       - "4318:4318"   # HTTP
#     depends_on:
#       - product-service
#       - cart-service
#       - order-service
#   tempo:
#     image: grafana/tempo:latest
#     user: root
#     ports:
#       - "3200:3200"
#       - "4319:4317"
#     entrypoint: ["/tempo", "-config.file=/etc/tempo.yaml"]
#         #    command: ["/tempo-entrypoint.sh"]
#     volumes:
#       - ./tempo.yaml:/etc/tempo.yaml
#       - tempo-data:/tmp/tempo
#         #      - ./tempo-entrypoint.sh:/tempo-entrypoint.sh
#   grafana:
#     image: grafana/grafana:latest
#     ports:
#       - "8080:3000"
#     environment:
#       - GF_SERVER_ROOT_URL=%(protocol)s://%(domain)s/
#       - GF_SERVER_SERVE_FROM_SUB_PATH=true
#       - GF_SECURITY_ALLOW_EMBEDDING=true
#       - GF_AUTH_ANONYMOUS_ENABLED=true
#       - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin   # 👈 Add this line
#     volumes:
#       - grafana-storage:/var/lib/grafana
#     depends_on:
#       - tempo

# volumes:
#   grafana-storage:
#   tempo-data: