apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: internal-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: asia-south1-docker.pkg.dev/observability-project-466314/observability-images/observability-demo_frontend:latest
        ports:
        - containerPort: 5000
        env:
        - name: NODE_IP
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP

---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: internal-app
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: ClusterIP