apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
  namespace: internal-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
      - name: order-service
        image: asia-south1-docker.pkg.dev/observability-project-466314/observability-images/observability-demo_order-service:latest
        ports:
        - containerPort: 5003
        env:
        - name: NODE_IP
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP

---
apiVersion: v1
kind: Service
metadata:
  name: order-service
  namespace: internal-app
spec:
  selector:
    app: order-service
  ports:
    - protocol: TCP
      port: 5003
      targetPort: 5003
  type: ClusterIP