apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-collector-config
  namespace: opentelemetry
data:
  otel-config.yaml: |
    receivers:
      otlp:
        protocols:
          http:
          grpc:

    processors:
      batch:
      resource:
        attributes:
          - action: insert
            key: gcp.project.name
            value: gke-demo
      k8sattributes:
        auth_type: serviceAccount
        extract:
          metadata: # extracted from the pod
            - k8s.namespace.name
            - k8s.pod.name
            - k8s.node.name
            - k8s.container.name
            - container.name  # ✅ supported
            - container.id  
        filter:
          namespace: internal-app


    exporters:
      googlecloud:
        project: "gke-demo-466215" #prj-cams-playground-devopspoc
        metric:
          prefix: "custom.googleapis.com"
        log:
          default_log_name: opentelemetry.io/collector-exported-log
        trace:
          attribute_mappings: []  # default
        user_agent: "otel-collector"

    service:
      pipelines:
        traces:
          receivers: [otlp]
          processors: [batch, resource, k8sattributes]
          exporters: [googlecloud]
        metrics:
          receivers: [otlp]
          processors: [batch, resource, k8sattributes]
          exporters: [googlecloud]
        logs:
          receivers: [otlp]
          processors: [batch, resource, k8sattributes]
          exporters: [googlecloud]