mode: daemonset

image:
  repository: otel/opentelemetry-collector-contrib
  tag: latest
  pullPolicy: IfNotPresent

command:
  - "/otelcol-contrib"
  - "--config=/etc/otel/config.yaml"
  - "--log-level=debug"

serviceAccount:
  create: true
  name: otel-collector-sa
  annotations:
    iam.gke.io/gcp-service-account: "gke-observability-sa@observability-project-466314.iam.gserviceaccount.com"

podAnnotations: {}

tolerations: []

nodeSelector: {}

affinity: {}

config: |
  receivers:
    otlp:
      protocols:
        http:
          endpoint: 0.0.0.0:4318
        grpc:
          endpoint: 0.0.0.0:4317

  processors:
    batch: {}
    resourcedetection:
      detectors: [gcp]
      timeout: 5s
    resource:
      attributes:
        - action: insert
          key: gcp.project.name
          value: observability-project-466314
    k8sattributes:
      passthrough: false
      filter:
        node_from_env_var: KUBE_NODE_NAME
      auth_type: serviceAccount
      pod_association:
        - sources:
            - from: connection
        - sources:
            - from: resource_attribute
              name: ip
        - sources:
            - from: resource_attribute
              name: k8s.pod.ip
      extract:
        metadata:
          - k8s.namespace.name
          - k8s.pod.name
          - k8s.node.name
          - k8s.container.name
          - k8s.deployment.name
          - k8s.pod.uid
        annotations:
          - key: my.annotation.key
            from: pod
        labels:
          - key: app
            from: pod
    attributes/k8s_to_labels:
      actions:
        - key: k8s.namespace.name
          from_attribute: k8s.namespace.name
          action: insert
        - key: k8s.pod.name
          from_attribute: k8s.pod.name
          action: insert
        - key: k8s.node.name
          from_attribute: k8s.node.name
          action: insert
        - key: k8s.deployment.name
          from_attribute: k8s.deployment.name
          action: insert
        - key: k8s.pod.uid
          from_attribute: k8s.pod.uid
          action: insert

  exporters:
    googlecloud:
      project: "observability-project-466314"
      metric:
        prefix: "custom.googleapis.com"
      log:
        default_log_name: opentelemetry.io/collector-exported-log
      trace:
        attribute_mappings: []
      user_agent: "otel-collector"
    debug:
      verbosity: detailed

  service:
    pipelines:
      traces:
        receivers: [otlp]
        processors: [resourcedetection, k8sattributes, attributes/k8s_to_labels, resource, batch]
        exporters: [googlecloud]
      metrics:
        receivers: [otlp]
        processors: [resourcedetection, k8sattributes, attributes/k8s_to_labels, resource, batch]
        exporters: [googlecloud]
      logs:
        receivers: [otlp]
        processors: [resourcedetection, k8sattributes, attributes/k8s_to_labels, resource, batch]
        exporters: [googlecloud, debug]
    telemetry:
      logs:
        level: "debug"
