image:
  repository: otel/opentelemetry-collector-contrib
  tag: latest
  pullPolicy: IfNotPresent

command:
  - "/otelcol-contrib"
  - "--config=/etc/otel/config.yaml"
  - "--log-level=debug"

serviceAccount:
  create: true
  name: otel-collector-sa
  annotations:
    iam.gke.io/gcp-service-account: "gke-observability-sa@observability-project-466314.iam.gserviceaccount.com"

podAnnotations: {}

tolerations: []

nodeSelector: {}

affinity: {}

config: |
  receivers:
    otlp:
      protocols:
        http:
          endpoint: 0.0.0.0:4318
        grpc:
          endpoint: 0.0.0.0:4317


  processors:
    batch: {}
    resource:
      attributes:
        - action: insert
          key: gcp.project.name
          value: observability-project-466314
    k8sattributes:
      auth_type: serviceAccount
      pod_association:
        - sources: # First try to use the value of the resource attribute k8s.pod.ip
        - sources:
            - from: resource_attribute
              name: k8s.pod.name
            - from: connection
      extract:
        metadata:
          - k8s.namespace.name
          - k8s.pod.name
          - k8s.node.name
          - k8s.container.name

  exporters:
    googlecloud:
      project: "observability-project-466314"
      metric:
        prefix: "custom.googleapis.com"
      log:
        default_log_name: opentelemetry.io/collector-exported-log
      trace:
        attribute_mappings: []
      user_agent: "otel-collector"

  service:
    pipelines:
      traces:
        receivers: [otlp]
        processors: [batch, resource, k8sattributes]
        exporters: [googlecloud]
      metrics:
        receivers: [otlp]
        processors: [batch, resource, k8sattributes]
        exporters: [googlecloud]
      logs:
        receivers: [otlp]
        processors: [batch, resource, k8sattributes]
        exporters: [googlecloud]
    telemetry:
      logs:
        level: "debug"