image:
  repository: otel/opentelemetry-collector-contrib
  tag: latest
  pullPolicy: IfNotPresent

command:
  - "/otelcol-contrib"
  - "--config=/etc/otel/config.yaml"
  - "--log-level=debug"

serviceAccount:
  create: true
  name: otel-collector-sa
  annotations:
    iam.gke.io/gcp-service-account: "gke-observability-sa@observability-project-466314.iam.gserviceaccount.com"

podAnnotations: {}

tolerations: []

nodeSelector: {}

affinity: {}

config: |
  receivers:
    otlp:
      protocols:
        http:
          endpoint: 0.0.0.0:4318
        grpc:
          endpoint: 0.0.0.0:4317


  processors:
    batch: {}
    resourcedetection:  # Add this processor
      detectors: [gke]  # Automatically detects GKE resources
      timeout: 5s
    resource:
      attributes:
        - action: insert
          key: gcp.project.name
          value: observability-project-466314
    k8sattributes:
      passthrough: false  # Important for enrichment
      filter:
        node_from_env_var: KUBE_NODE_NAME  # Required for node filtering
      auth_type: serviceAccount
      pod_association:
          # Try these association rules in order
          - sources:
              - from: connection
          - sources:
              - from: resource_attribute
                name: ip
          - sources:
              - from: resource_attribute
                name: k8s.pod.ip
      extract:
        metadata:
          - k8s.namespace.name
          - k8s.pod.name
          - k8s.node.name
          - k8s.container.name
          - k8s.deployment.name  # Add this
          - k8s.pod.uid  # Add this for better correlation
  exporters:
    googlecloud:
      project: "observability-project-466314"
      metric:
        prefix: "custom.googleapis.com"
      log:
        default_log_name: opentelemetry.io/collector-exported-log
      trace:
        attribute_mappings: []
      user_agent: "otel-collector"

  service:
    pipelines:
      traces:
        receivers: [otlp]
        processors: [resourcedetection, k8sattributes, resource, batch]  # Correct order
        exporters: [googlecloud]
      metrics:
        receivers: [otlp]
        processors: [resourcedetection, k8sattributes, resource, batch]  # Correct order
        exporters: [googlecloud]
      logs:
        receivers: [otlp]
        processors: [resourcedetection, k8sattributes, resource, batch]  # Correct order
        exporters: [googlecloud]
    telemetry:
      logs:
        level: "debug"