mode: daemonset

image:
  repository: otel/opentelemetry-collector-contrib
  tag: latest
  pullPolicy: IfNotPresent

serviceAccount:
  create: true
  name: otel-collector-sa
  annotations:
    iam.gke.io/gcp-service-account: "gke-observability-sa@observability-project-466314.iam.gserviceaccount.com"

config: |
  receivers:
    otlp:
      protocols:
        grpc:
        http:

  processors:
    batch:
    k8sattributes:
    resource:
    filter/drop-non-app-logs:
      logs:
        include:
          match_type: strict
          resource_attributes:
            - key: service.name
              value: your-app-name  # ✅ Replace with your real app service.name

  exporters:
    googlecloud:
      log:
        default_log_name: "application_logs"

  extensions: {}  # disables all default extensions like health_check, zpages, etc.

  service:
    telemetry:
      logs:
        level: "none"
      metrics:
        level: "none"

    pipelines:
      logs:
        receivers: [otlp]
        processors: [filter/drop-non-app-logs, batch, resource, k8sattributes]
        exporters: [googlecloud]
