image:
  repository: otel/opentelemetry-collector-contrib
  tag: latest
  pullPolicy: IfNotPresent

serviceAccount:
  create: true
  name: otel-collector-sa
  annotations:
    iam.gke.io/gcp-service-account: "gke-observability-sa@observability-project-466314.iam.gserviceaccount.com"

podAnnotations: {}

tolerations: []

nodeSelector: {}

affinity: {}

# Set OpenTelemetry Collector's internal log level
logLevel: info

config: |
  receivers:
    otlp:
      protocols:
        http:
          endpoint: 0.0.0.0:4318
        grpc:
          endpoint: 0.0.0.0:4317

  processors:
    batch:
      verbosity: detailed
    resource:
      verbosity: detailed
      attributes:
        - action: insert
          key: gcp.project.name
          value: observability-project-466314
    k8sattributes:
      verbosity: detailed
      auth_type: serviceAccount
      pod_association:
        - sources:
            - from: connection
      extract:
        metadata:
          - k8s.namespace.name
          - k8s.pod.name
          - k8s.node.name
          - k8s.container.name

  exporters:
    googlecloud:
      verbosity: detailed
      project: "observability-project-466314"
      metric:
        prefix: "custom.googleapis.com"
      log:
        default_log_name: opentelemetry.io/collector-exported-log
      trace:
        attribute_mappings: []
      user_agent: "otel-collector"

  service:
    pipelines:
      traces:
        receivers: [otlp]
        processors: [batch, resource, k8sattributes]
        exporters: [googlecloud]
      metrics:
        receivers: [otlp]
        processors: [batch, resource, k8sattributes]
        exporters: [googlecloud]
      logs:
        receivers: [otlp]
        processors: [batch, resource, k8sattributes]
        exporters: [googlecloud]
